volumes: 
  data_blog_dev:
  shared_blog_data:

services:
  db:
    image: postgres:12-bullseye
    container_name: blog1
    volumes:
      - data_blog_dev:/var/lib/postgresql/data
      - shared_blog_data:/var/shared
    env_file: .env
    ports: 
      - "5432:5432"